### ISSUE TITLE
A new state machine for each instance of a component

### ISSUE THREAD

**Issue by dfeyer** [krasimir/stent#11]
First, thanks for creating stent, really intersting pattern.

Did you try / is it possible to use Stent to manage complex component internal state ? I collaborate with Neos CMS (neos.io), and we have some really complex components (image editor, ...) that can gain a lots to have state machine to manage their internal state. 

I successfully build a prototype, but as the machine need to be named, all compoment get the same machine, by default.

**Comment by krasimir** [comment]
Hey, thank you for using the library. There is an [API](https://github.com/krasimir/stent/blob/master/docs/machine.md) where you don't name the machine. It comes with a auto-generated unique name.

```js
const appMachine = Machine.create(
  // initial state
  <state object>,
  // transitions
  {
    <state name>: {
      <action name>: <action handler>,
      <action name>: <action handler>,
      ...
    },
    <state name>: {
      <action name>: <action handler>,
      <action name>: <action handler>,
      ...
    },
    ...
  }
);
```

Here's a bit from the [example](https://github.com/krasimir/stent/blob/master/examples/todo-app/src/components/ToDo.js) that comes with the library:

```js
this._machine = Machine.create(
      { name: 'idle' },
      {
        idle: { edit: 'editing' },
        editing: {
          save: (state, newLabel) => {
            props.editTodo(props.index, newLabel);
            return 'idle';
          },
          cancel: 'idle'
        }
      }
    );
```
