### ISSUE TITLE
Camel cased transitions do not produce handlers

### ISSUE THREAD

**Issue by aryzing** [krasimir/stent#13]
While attempting to name a transition `startProcess`, I found that the `connect` mappings did not produce a handler for this transition. After renaming it to `"start process"`, the `startProcess()` handler was mapped as expected.

Are state names not allowed in camel case? 

After reading the docs, I was expecting the behavior to be:

* if spaces exist in transition name -> transform to camel case
* if dashes exist in transition name -> transform to camel case
* else -> leave as is

**Comment by krasimir** [comment]
That's for sure a bug. I'll try to fix it asap.

**Comment by krasimir** [comment]
@aryzing can you please try the new 5.0.3 version. Should fix the problem.

P.S.
by the way I'm interested in receiving feedback for the library. In what cases you guys used it. Is it working for you and so on.

**Comment by aryzing** [comment]
Thanks for the quick fix! I'll update to the latest version now. 

I'll catch up with you with feedback later: I only started working with it yesterday, but so far so good, I'm liking it quite a lot 👍

**Comment by poteirard** [comment]
Just tested. It works as expected 👍  Good job guys !
