### ISSUE TITLE
[question] how to get additional empty variable inside state

### ISSUE THREAD

**Issue by menteora** [krasimir/stent#14]
Hi, thank you for your work and your good choice: mealy-machine!  

I've a little question, I've create new Machine thats work inside Vue.js!  
Now I want to get additional parameter `parentAction = new ` inside the state.

```
var stent = Machine.create('actions', {
  state: { name: 'start', parentAction: 'new' },
  transitions: {
    'start': {
      'take note': 'note',
      'create ordine': 'order',
      'take party': 'party'
    },
    'note': {
      'take another note': 'note',
      'create order': 'order',
      'take party': 'party'
    },
    'party': {
      'add participant': { name: 'participant', parentAction: 'new' }
    },
    'participant': {
      'create ordine'': 'order',
      'add participant': 'participant',
    },
...
```

The first state `start` has `stent.state.parentAction = 'new'`, correct,
but when I change the state to `note` the `stent.state.parentAction` is always `new`.
There is a way to get `undefined, null, empty` variable for states that haven't `stent.state.parentAction` defined?

**Comment by krasimir** [comment]
Hey, that's probably a bug. I'll investigate and get back to you asap.

**Comment by menteora** [comment]
To simplify, here's my issue simulated without vuejs: https://runkit.com/menteora/stent-issue14

**Comment by krasimir** [comment]
Hey I think I misunderstood your use case. That's how it works by design. If you use the short notation for changing state only the `name` property is updated keeping the rest untouched. In order to remove/change `parentAction` you have to use an object, function or a generator. For example:

```js
var { Machine } = require("stent");

var stent = Machine.create('actions', {
  state: { name: 'start', parentAction: 'new' },
  transitions: {
    'start': {
      'take note': { name: 'note' }
    },
    'note': {
      'take another note': { name: 'note', parentAction: null }
    }
  }
})

const appMachine = Machine.get('actions');
console.log(appMachine.state.name, appMachine.state.parentAction);
appMachine.takeNote();
console.log(appMachine.state.name, appMachine.state.parentAction);
appMachine.takeAnotherNote();
console.log(appMachine.state.name, appMachine.state.parentAction);
```

![image](https://user-images.githubusercontent.com/528677/36011926-50a6e668-0d63-11e8-9e2d-270927c16de1.png)

**Comment by menteora** [comment]
Great! I totally missed this particular, sorry. 
Thank you!

**Comment by krasimir** [comment]
No worries. Let me know if something else is not working as expected.
