### ISSUE TITLE
Question: Is there a way to know if a transaction can be applied?

### ISSUE THREAD

**Issue by poteirard** [krasimir/stent#15]
Hi,

First of all thanks for your work. I wanted to know if there's a way to know if a transaction can be applied? Something like `transactionCanBeApplied()` ?

**Comment by krasimir** [comment]
Right now no but that's a good feature request. I'll implement it. Stay tuned.

**Comment by krasimir** [comment]
The new `5.1.0` version supports `is<action name>Allowed()` method. For example:

```js
{
  'idle': {
    'please run': 'running'
  },
  'running': {
    'stop please': 'idle'
  }
}
```

The machine has:

```js
machine.isPleaseRunAllowed();
machine.isStopPleaseAllowed();
```

Even tho now this is possible can you please give some more context. I have the feeling that the usage of these helper methods may be avoided.
