### ISSUE TITLE
Question: is it possible to execute code "on state change"

### ISSUE THREAD

**Issue by poteirard** [krasimir/stent#16]
Hi,

One question, is it possible to execute code before entering to specific state.

I have a state machine which every state has a transition like `next` that execute some code (a http request) and then transition to the next state. However I want to check the state before actually reaching that state, let's say to check if the state has X prop.

Is that possible without creating a transition like "checkingState"? Somehow like a specific callback? I saw that I can use middleware but I'm not sure if I can really achieve that like this.

Thank you 👍

**Comment by krasimir** [comment]
Is it like in your `next` handler you know what's the next state and wanna check a prop in it? Can you give some more concrete example.

**Comment by poteirard** [comment]
Sure. 

We are using your library to control the state of big form which has steps. Each steps is a page.

Each step represent 1 state. 

Every state has a transaction `next` and `previous`.

Every `next` has his own logic implementation.

```js
// Order of the steps, just to be able to change it for business decisions
const STEPS  = ['Step1', 'Step2', 'Step3']; 

const machine = Machine.create('app', {
  state: { name: 'idle', fields: {} },
  transitions: {
    'idle': {
      'startForm': goToFirstStep(),
   'Step1': {
      'next': submitFormAndGoToNextStep,
      'previous': goToPreviousStep,
    },
    'Step2': {
      'next': submitFormAndGoToNextStep,
      'previous': goToPreviousStep,
    },
    'Step2': {
      'next': submitFormAndGoToNextStep,
      'previous': goToPreviousStep,
    },
});
```
Now imagine I want to go from step1 to step2 but before I do that I want do check if the the user has already submitted the form of the Step2 because if so it should go to the Step3.

**Comment by krasimir** [comment]
First of all sorry for the late reply. Here's what I'm thinking:

* You first have to define what it means *state* for your app. From my point of view that is the current step and that `fields` object which probably contains your form data.
* Then in your `submitFormAndGoToNextStep` you have to check if the step that is coming next is already filled in. Or in other words I think you need a little bit smarter handler of the `next` action.

For example:

```js
const STEPS = [
  { name: 'Step1', fields: ['firstName', 'lastName'] },
  { name: 'Step2', fields: ['age', 'sex'] },
  { name: 'Step3', fields: ['address'] },
];

// later in your `next` handler
const submitFormAndGoToNextStep = function (state) {
  const currentPage = state.currentPage;
  const nextPage = STEPS[currentPage + 1];
  const doIHaveTheDataAlready = nextPage.fields.every(field => state.fields[field]);

  if (doIHaveTheDataAlready) {
    return { ...state, currentPage: currentPage + 2 }
  }
  return { ...state, currentPage: currentPage + 1 }
}
```

Like checking if the next step's fields are already in the `fields` object. Does this makes sense?

**Comment by poteirard** [comment]
The problem here is that if you have 30 steps you will have to make 30 conditionals like ` if (doIHaveTheDataAlready) {`. That's why it would be good to have like a callback for every state change in the steps.

**Comment by krasimir** [comment]
I see. I do understand your problem but I'll push back a little bit here. Sorry about that. It is easy to implement such logic. I mean hooks for when you are about to enter or leave a state. However, that is against the idea of the library. You are actually right. You do need a new transition because your current step IS actually in a third state. It's a state in which the user fills the data and moves forward.  At this point you have to make a decision based on the app data. Such cases where you make decisions are good candidates for separate states. What you think?

**Comment by poteirard** [comment]
I think you are right. 
I just pointed out this because I used other state machine libraries in the past that offers those 'hooks' (Example: http://finite.readthedocs.io/en/master/examples/callbacks.html). But if you don't want to include this functionality I totally understand it. Thanks for your help anyways :)

**Comment by krasimir** [comment]
Yep. Thanks for the understanding. I just feel that a little bit of a anti-pattern.
