### ISSUE TITLE
Getting  bundling failed: ReferenceError: Unknown plugin "babel-plugin-add-module-exports" specified in node_modules/stent/.babelrc

### ISSUE THREAD

**Issue by ValentinBlokhin** [krasimir/stent#20]
Is it possible to remove .babelrc from npm? It's not possible to build application using react native.
If I remove .babelrc from node_modules it works fine. 
Thanks!

**Comment by krasimir** [comment]
Sorry, for the delay. `5.1.1` released where `.babelrc` is ignored.
