### ISSUE TITLE
Make action handlers pure functions

### ISSUE THREAD

**Issue by thekarel** [krasimir/stent#23]
First of all, thanks for creating this library @krasimir, it seems to be a very powerful and expressive solution.

When looking at [action handlers](https://github.com/krasimir/stent/blob/master/docs/action-handler.md) I've noticed they are [bound to a context](https://github.com/krasimir/stent/blob/master/src/helpers/handleAction.js#L33). Would you consider making them pure functions, i.e. passing the whole `machine` as the first argument? (this was mentioned previously [in a comment](http://krasimirtsonev.com/blog/article/getting-from-redux-to-state-machine-with-stent#comment-3982990466))

So instead of 

`transitions[state.name][action].apply(machine, [ machine.state, ...payload ])`

pass everything as an argument, something like this?

`transitions[state.name][action](machine, payload)`

The benefit would be having pure functions as handlers, so they would be really easy to unit tests and maybe even a bit more consistent since now parts of the machine are passed as argument (`state`) and some parts as context (under `this`).

Handlers would then be able to pick up the relevant bits as in `const handler = ({state}) => ({...})`

I understand this would be an API breaking change, but maybe something to think about for the future?

**Comment by krasimir** [comment]
Actually that's better. Thank you for the suggestion. I'll make that change and will release a new major version. Indeed seems like a better design decision.

P.S.
My initial idea was to make the handlers as close to redux reducers as possible. That's why I took that decision.

**Comment by thekarel** [comment]
Thanks for your positive feedback! I'm happy to contribute with a PR, just wanted to ask for your opinion beforehand.

**Comment by krasimir** [comment]
Yep. Sounds legit.
