### ISSUE TITLE
impossible to catch the error if a generator function invokes call() with a non-function argument 

### ISSUE THREAD

**Issue by illarionvk** [krasimir/stent#27]
I get unhelpful errors from Node that slip past the try/catch block if the state action generator function invokes `call()` helper with an argument that is not a function (see screenshot).

Please take a look at [my pull request](https://github.com/krasimir/stent/pull/26) with a failing test that illustrates the behavior.

I think the call() helper should throw if the argument is not a function before returning the `__call` object.

P.S. I enjoy working with your library. Thank you for open-sourcing it.

![unhelpful-error](https://user-images.githubusercontent.com/5012724/51690821-c9889500-1ff9-11e9-8fee-ff32e5a18463.png)

![failing-test](https://user-images.githubusercontent.com/5012724/51690828-d0170c80-1ff9-11e9-86da-dd4ff4b26d80.png)

**Comment by krasimir** [comment]
`6.0.1` released containing the fix. One more time than you for the test. The fix is [here](https://github.com/krasimir/stent/commit/15fd09a364b2461e006e30512b61c74fda7f5970#diff-9c6855c17906b80b16db5f54595088b6R35)
