### ISSUE TITLE
componentWillMount is deprecated

### ISSUE THREAD

**Issue by sinxwal** [krasimir/stent#28]
Hi. I get warning when using "stent/lib/react":
`componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.`

I think we can safely replace componentWillMount with componentDidMount.

**Comment by krasimir** [comment]
Sorry for the super late response. I just migrated Stent to the latest React. The bit that uses React is now refactored to use hooks. There is a new version `7.0.0` released.
