### ISSUE TITLE
How to make State Machine table?

### ISSUE THREAD

**Issue by jiajianrong** [krasimir/stent#29]
In this [article](https://krasimirtsonev.com/blog/article/getting-from-redux-to-state-machine-with-stent),
it demonstrates a SM table in the `login form`.

But in real cases, it's hard to define the SM table. For instance, I have a user form cantaining 4 inputs
(name, age, company, salary):

```
<formItem>
    <input name="salary" onBlur={checkSalary}>
    <Hint>{salaryErrHint}</Hint>
</formItem


checkSalary(e) {
    ...
    if (...)
        this.setState({
            salaryErrHint: 'salary is required'
        })
    else if (...)
        this.setState({
            salaryErrHint: 'salary must be a number'
        })
    else if (...)
        this.setState({
            salaryErrHint: 'salary must be less than 10000000'
        })
    else
        this.setState({
            salaryErrHint: ''
        })
}

```

In above demo I will define 4 `errHint` states in pure react code.
I want to optimize the code with SM, but I wonder if the below SM chart is appropriate?

```
UserForm   -->   input.wrong.name     -->  UserForm with nameErrHint
UserForm   -->   input.wrong.age      -->  UserForm with ageErrHint
UserForm   -->   input.wrong.company  -->  UserForm with companyErrHint
UserForm   -->   input.wrong.salary   -->  UserForm with saralyErrHint
```

I can't see the advantage from the SM table. Thank you in advance.

**Comment by krasimir** [comment]
I would go with a single error state and maybe store the reason of failure. The Machine doesn't need to know what exactly failed.
