### ISSUE TITLE
Connected React component is not reconnecting to the machine(s) on remount

### ISSUE THREAD

**Issue by illarionvk** [krasimir/stent#38]
The [React `connect` helper](https://github.com/krasimir/stent/blob/master/docs/react-integration.md) connects the component to the machine only once at the time when the HoC is created.

The HoC disconnects from the machine(s) when it unmounts, but does not reconnect if we mount the same component again.

**Comment by illarionvk** [comment]
The bug was originally discovered by @SofianeDjellouli

**Comment by krasimir** [comment]
Thanks. 8.0.1 released.
