### ISSUE TITLE
Issue when calling action while a generator is awaiting a response and yields after previous action changes state

### ISSUE THREAD

**Issue by flipace** [krasimir/stent#4]
I'm not sure whether I'm doing something wrong here or misunderstood a concept, so please correct me if I'm on the wrong path here.

I have a machine with an idle state which has a couple of transitions:
handle password, handle email -> they all just update the idle states current data  (so that username etc. are updated).
Then there's a "handle username" transition which is a generator function which checks whether the username is available or not.

Now - if i trigger e.g. "handle password" and update the states password value, and I do this while the handle username function is still awaiting a response from the network request - as soon as the network request is done, i yield a state like

```js
{...state, errors: { ...state.errors, username: error } }
```

Now, even though the state changed in between, this will set the password value back to the value it used to have before the handle username action was called.

If I use `machine.state` however it works well. Maybe adding a "getState()" function would be a viable addition for actions (if I didn't miss anything else here :))

Thanks in advance for your help - I really enjoy using stent with React!

**Comment by krasimir** [comment]
Hey @flipace,

Every action handler is run with the machine as context. So inside your generator you may use `this.state` and you'll get the current state of the machine. For example:
```js
'handle username': function * (state, username) {
  try {
    yield call(remoteService.something, username);
  } catch(error) {
    yield { ...this.state, errors: { ...state.errors, username: error }};
  }
}
```
Let me know if if that works for you.

**Comment by flipace** [comment]
Awesome, thanks @krasimir! It works with the context state!

**Comment by krasimir** [comment]
You are welcome.
