### ISSUE TITLE
Errors in the function result of the call helper are not caught

### ISSUE THREAD

**Issue by SofianeDjellouli** [krasimir/stent#47]
Hi,

In the `handleGenerator` function, the [function result](https://github.com/krasimir/stent/blob/13e0fc53e955c699deb9aa721c762e2e843d0cb1/src/helpers/handleGenerator.js#L31) of the `call` helper is evaluated without catching the errors it may throw. Therefore, if it throws an error, the `handleGenerator`'s function execution will stop.

Please have a look at my PR: [#46](https://github.com/krasimir/stent/pull/46)

**Comment by krasimir** [comment]
Thanks. Released as `8.0.3`.
